import spotipy
from spotipy.oauth2 import SpotifyOAuth
import random

def collaborative_filtering(sp):
    # Get the user's top artists
    top_artists = sp.current_user_top_artists(limit=5)

    # Print user's favorite artists
    print("Your favorite artists:")
    for i, artist in enumerate(top_artists['items'], 1):
        print(f"{i}. {artist['name']}")

    # Get the top tracks of similar users based on their top artists
    similar_users_tracks = []
    for artist in top_artists['items']:
        tracks = sp.artist_top_tracks(artist['id'], country='US')['tracks']
        similar_users_tracks.extend(tracks)

    # Return the recommended tracks from similar users' top tracks
    return similar_users_tracks


def content_filtering(sp, danceability, energy, valence, user_genres, novelty_factor):
    # Generate recommendations based on target attributes, user preferences, and personalized genres
    recommendations = sp.recommendations(seed_genres=user_genres, limit=10,
                                         target_danceability=danceability,
                                         target_energy=energy,
                                         target_valence=valence)
    
    # Introduce novelty by selecting additional tracks from lesser-explored genres or artists
    novelty_tracks = []
    if novelty_factor > 0.0:
        for genre in user_genres:
            tracks = sp.recommendations(seed_genres=[genre], limit=int(novelty_factor * 10))['tracks']
            novelty_tracks.extend(tracks)

    return recommendations['tracks'] + novelty_tracks


def generate_playlist():
    # Prompt the user to enter their Spotify API credentials
    CLIENT_ID = input("Enter your Spotify API client ID: ")
    CLIENT_SECRET = input("Enter your Spotify API client secret: ")
    REDIRECT_URI = input("Note: Standard URI = http://localhost:3000/" + '\n' "Enter your Spotify API redirect URI: ")
    USER_ID = input("Note: You can find your user ID by clicking on your profile in the Spotify app." + '\n' "Enter your Spotify user ID: ")
    PLAYLIST = input("Enter the name of your new playlist: ")

    # Scope: the access rights you want for your application
    SCOPE = 'playlist-modify-private playlist-read-private user-top-read user-read-recently-played'

    # Create an instance of the SpotifyOAuth class
    sp_oauth = spotipy.oauth2.SpotifyOAuth(CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, scope=SCOPE)

    # Generate the authorization URL
    auth_url = sp_oauth.get_authorize_url()

    # Ask the user to grant access via the generated URL
    print("Visit this URL and grant access:")
    print(auth_url)
    response = input("Enter the full URL you received after authorization: ")

    # Exchange the authorization code for an access token
    code = sp_oauth.parse_response_code(response)
    token_info = sp_oauth.get_access_token(code)

    # Get the access token from the token information
    access_token = token_info['access_token']

    # Create a Spotify object with the access token
    sp = spotipy.Spotify(auth=access_token)

    # Step 1: Retrieve user preferences for danceability, energy, valence, and novelty
    danceability = float(input("How important is danceability (0.0 - 1.0)? "))
    energy = float(input("How important is energy (0.0 - 1.0)? "))
    valence = float(input("How important is valence (0.0 - 1.0)? "))
    novelty_factor = float(input("How important is novelty (0.0 - 1.0)? "))

    # Step 2: Prompt the user to choose the playlist generation method
    method = input("Choose playlist generation method (enter 'genres' or 'artists'): ")

    # Step 3: Perform collaborative filtering or content filtering based on the chosen method
    if method == "genres":
        user_genres = input("Enter your preferred genres (comma-separated): ").split(",")
        recommendations = content_filtering(sp, danceability, energy, valence, user_genres, novelty_factor)
    elif method == "artists":
        recommendations = collaborative_filtering(sp)
    else:
        print("Invalid method chosen. Exiting...")
        return

    # Step 4: Create a new private playlist
    playlist = sp.user_playlist_create(USER_ID, PLAYLIST, public=False,
                                       description='Playlist generated by Playlistify')

    # Step 5: Add the recommended tracks to the playlist in a shuffled order
    random.shuffle(recommendations)
    track_ids = [track['id'] for track in recommendations]
    sp.playlist_add_items(playlist['id'], track_ids)

    print("Playlist is generated and tracks are added.")


# Call the generate_playlist function to generate a playlist
generate_playlist()
