import spotipy
from spotipy.oauth2 import SpotifyOAuth
import random

def collaborative_filtering(sp):
    # Get the user's top artists
    top_artists = sp.current_user_top_artists(limit=5)

    # Print user's favorite artists
    print("Your favorite artists:")
    for i, artist in enumerate(top_artists['items'], 1):
        print(f"{i}. {artist['name']}")

    # Get the top tracks of similar users based on their top artists
    similar_users_tracks = []
    for artist in top_artists['items']:
        tracks = sp.artist_top_tracks(artist['id'], country='US')['tracks']
        similar_users_tracks.extend(tracks)

    # Return the recommended tracks from similar users' top tracks
    return similar_users_tracks


def content_filtering(sp, danceability, energy, valence, user_genres):
    # Generate recommendations based on target attributes, user preferences, and personalized genres
    recommendations = sp.recommendations(seed_genres=user_genres, limit=10,
                                         target_danceability=danceability,
                                         target_energy=energy,
                                         target_valence=valence)

    return recommendations['tracks']

def get_user_top_genres(sp):
    # Get the user's top tracks
    top_tracks = sp.current_user_top_tracks(limit=50, time_range='medium_term')

    # Extract the genres from the top tracks
    genres = []
    for track in top_tracks['items']:
        genres.extend(track['artists'][0]['genres'])

    # Count the occurrences of each genre
    genre_counts = {}
    for genre in genres:
        genre_counts[genre] = genre_counts.get(genre, 0) + 1

    # Sort the genres based on their occurrence count
    sorted_genres = sorted(genre_counts.items(), key=lambda x: x[1], reverse=True)

    # Return the top genres
    top_genres = [genre[0] for genre in sorted_genres[:5]]
    return top_genres


def generate_playlist():
    # Prompt the user to enter their Spotify API credentials
    CLIENT_ID = input("Enter your Spotify API client ID: ")
    CLIENT_SECRET = input("Enter your Spotify API client secret: ")
    REDIRECT_URI = input("Enter your Spotify API redirect URI: ")
    USER_ID = input("Enter your Spotify user ID: ")
    PLAYLIST = input("Enter the name of your new playlist: ")

    # Scope: the access rights you want for your application
    SCOPE = 'playlist-modify-private playlist-read-private user-top-read user-read-recently-played'

    # Create an instance of the SpotifyOAuth class
    sp_oauth = spotipy.oauth2.SpotifyOAuth(CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, scope=SCOPE)

    # Generate the authorization URL
    auth_url = sp_oauth.get_authorize_url()

    # Ask the user to grant access via the generated URL
    print("Visit this URL and grant access:")
    print(auth_url)
    response = input("Enter the full URL you received after authorization: ")

    # Exchange the authorization code for an access token
    code = sp_oauth.parse_response_code(response)
    token_info = sp_oauth.get_access_token(code)

    # Get the access token from the token information
    access_token = token_info['access_token']

    # Create a Spotify object with the access token
    sp = spotipy.Spotify(auth=access_token)

    # Step 1: Retrieve user preferences for danceability, energy, and valence
    danceability = float(input("How important is danceability (0.0 - 1.0)? "))
    energy = float(input("How important is energy (0.0 - 1.0)? "))
    valence = float(input("How important is valence (0.0 - 1.0)? "))

    # Step 2: Perform collaborative filtering to generate recommendations
    collaborative_recommendations = collaborative_filtering(sp)

    # Step 3: Retrieve user's top genres based on their listening history
    user_genres = get_user_top_genres(sp)

    # Step 4: Perform content filtering to generate recommendations
    content_recommendations = content_filtering(sp, danceability, energy, valence, user_genres)

    # Combine the recommendations from both techniques
    combined_recommendations = collaborative_recommendations + content_recommendations

    # Step 5: Create a new private playlist
    playlist = sp.user_playlist_create(USER_ID, PLAYLIST, public=False,
                                       description='Playlist generated by Playlistify')

    # Step 6: Add the recommended tracks to the playlist in a shuffled order
    random.shuffle(combined_recommendations)
    track_ids = [track['id'] for track in combined_recommendations]
    sp.playlist_add_items(playlist['id'], track_ids)

    print("Playlist is generated and tracks are added.")
    

# Call the generate_playlist function to generate a playlist
generate_playlist()